In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import optuna
from optuna_integration import OptunaSearchCV
from scikeras.wrappers import KerasClassifier

In [2]:
# All the data processing, preprocessing activities are similar to Machine Learning Models

In [3]:
# Standardization - ANN -- Help the neural to process the compute fast
# Function will converge fast

In [4]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\sneha\anaconda assignment\excel\Churn_Modelling.csv')

In [5]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [6]:
dataset_new = dataset.drop(columns = ['Geography', 'RowNumber', 'CustomerId','Surname','Gender'])

In [7]:
dataset_new

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1
3,699,39,1,0.00,2,0,0,93826.63,0
4,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0
9996,516,35,10,57369.61,1,1,1,101699.77,0
9997,709,36,7,0.00,1,0,1,42085.58,1
9998,772,42,3,75075.31,2,1,0,92888.52,1


In [8]:
X = dataset_new.iloc[:, 0:10].values
y = dataset_new.Exited.values

In [9]:
X

array([[6.1900000e+02, 4.2000000e+01, 2.0000000e+00, ..., 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00],
       [6.0800000e+02, 4.1000000e+01, 1.0000000e+00, ..., 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00],
       [5.0200000e+02, 4.2000000e+01, 8.0000000e+00, ..., 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00],
       ...,
       [7.0900000e+02, 3.6000000e+01, 7.0000000e+00, ..., 1.0000000e+00,
        4.2085580e+04, 1.0000000e+00],
       [7.7200000e+02, 4.2000000e+01, 3.0000000e+00, ..., 0.0000000e+00,
        9.2888520e+04, 1.0000000e+00],
       [7.9200000e+02, 2.8000000e+01, 4.0000000e+00, ..., 0.0000000e+00,
        3.8190780e+04, 0.0000000e+00]], shape=(10000, 9))

In [10]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
# Feature Scaling

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
# Modelling phase

In [13]:
Dense?

Init signature:
Dense(
    units,
    activation=None,
    use_bias=True,
    kernel_initializer='glorot_uniform',
    bias_initializer='zeros',
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    lora_rank=None,
    lora_alpha=None,
    quantization_config=None,
    **kwargs,
)
Docstring:     
Just your regular densely-connected NN layer.

`Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer
(only applicable if `use_bias` is `True`). When this layer is
followed by a `BatchNormalization` layer, it is recommended to set
`use_bias=False` as `BatchNormalization` has its own bias term.

Note: If the input to the layer has a rank greater than 2, `Dense`
computes the dot product

In [14]:
#[9,6,6,1]  =
# Setting up the Networks
#Initializing Neural Network
classifier = Sequential()   #Feed forward neural networks

classifier.add(Dense(units = 6, activation = 'relu', input_dim = 9))  # First Hidden Layer
classifier.add(Dense(units = 6, activation = 'relu'))
classifier.add(Dense(units = 1, activation = 'sigmoid'))

C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
# adam, adamW, GradientDescent  - Hyperparamter
# loss function
# metrics - accuracy, F1 score

In [16]:
classifier.compile?

Signature:
classifier.compile(
    optimizer='rmsprop',
    loss=None,
    loss_weights=None,
    metrics=None,
    weighted_metrics=None,
    run_eagerly=False,
    steps_per_execution=1,
    jit_compile='auto',
    auto_scale_loss=True,
)
Docstring:
Configures the model for training.

Example:

```python
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=[
        keras.metrics.BinaryAccuracy(),
        keras.metrics.FalseNegatives(),
    ],
)
```

Args:
    optimizer: String (name of optimizer) or optimizer instance. See
        `keras.optimizers`.
    loss: Loss function. May be a string (name of loss function), or
        a `keras.losses.Loss` instance. See `keras.losses`. A
        loss function is any callable with the signature
        `loss = fn(y_true, y_pred)`, where `y_true` are the ground truth
        values, and `y_pred` are the model's predictions.
        `y_true` should have shape `(batch_siz

In [17]:
# Compiling Neural Network - Setting up Loss and Optimizers
classifier.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
# in one round how may records should pass for training
# 500, 20 iterations

In [19]:
classifier.fit?

Signature:
classifier.fit(
    x=None,
    y=None,
    batch_size=None,
    epochs=1,
    verbose='auto',
    callbacks=None,
    validation_split=0.0,
    validation_data=None,
    shuffle=True,
    class_weight=None,
    sample_weight=None,
    initial_epoch=0,
    steps_per_epoch=None,
    validation_steps=None,
    validation_batch_size=None,
    validation_freq=1,
)
Docstring:
Trains the model for a fixed number of epochs (dataset iterations).

Args:
    x: Input data. It can be:
        - A NumPy array (or array-like), or a list of arrays
        (in case the model has multiple inputs).
        - A backend-native tensor, or a list of tensors
        (in case the model has multiple inputs).
        - A dict mapping input names to the corresponding array/tensors,
        if the model has named inputs.
        - A `keras.utils.PyDataset` returning `(inputs, targets)` or
        `(inputs, targets, sample_weights)`.
        - A `tf.data.Dataset` yielding `(inputs, targets)` or
       

In [20]:
# Fitting our model - Training
classifier.fit(X_train, y_train, batch_size = 500, epochs = 20, validation_data=[X_test, y_test])

Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.3848 - loss: 1.0186 - val_accuracy: 0.4395 - val_loss: 0.9150
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5110 - loss: 0.8308 - val_accuracy: 0.5460 - val_loss: 0.7665
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6071 - loss: 0.7098 - val_accuracy: 0.6500 - val_loss: 0.6667
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6896 - loss: 0.6258 - val_accuracy: 0.7235 - val_loss: 0.5950
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7600 - loss: 0.5635 - val_accuracy: 0.7870 - val_loss: 0.5402
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8198 - loss: 0.5146 - val_accuracy: 0.8380 - val_loss: 0.4958
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8635 - loss: 0.4742 - val_accuracy: 0.8795 - val_loss: 0.4582
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8944 - loss: 0.4392 - val_accuracy: 0.9080 - va

In [21]:
# Parameters eligible for tuning
# Layers
# Neurons
# activation function
# optimizer
# batch_size
# epoch

In [22]:
# Predicting the Test set results # prediction
y_pred = classifier.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [23]:
y_pred

array([[0.14339134],
       [0.01178862],
       [0.1288762 ],
       ...,
       [0.16156034],
       [0.24672   ],
       [0.18248221]], shape=(2000, 1), dtype=float32)

In [24]:
y_test

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [25]:
y_pred = (y_pred > 0.5)

In [26]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], shape=(2000, 1))

In [27]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [28]:
cm

array([[1598,    0],
       [   6,  396]])

In [29]:
X

array([[6.1900000e+02, 4.2000000e+01, 2.0000000e+00, ..., 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00],
       [6.0800000e+02, 4.1000000e+01, 1.0000000e+00, ..., 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00],
       [5.0200000e+02, 4.2000000e+01, 8.0000000e+00, ..., 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00],
       ...,
       [7.0900000e+02, 3.6000000e+01, 7.0000000e+00, ..., 1.0000000e+00,
        4.2085580e+04, 1.0000000e+00],
       [7.7200000e+02, 4.2000000e+01, 3.0000000e+00, ..., 0.0000000e+00,
        9.2888520e+04, 1.0000000e+00],
       [7.9200000e+02, 2.8000000e+01, 4.0000000e+00, ..., 0.0000000e+00,
        3.8190780e+04, 0.0000000e+00]], shape=(10000, 9))

In [30]:
# Predicting the Test set results
y_pred_train = classifier.predict(X_train)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [31]:
y_pred_train = (y_pred_train > 0.5)

In [32]:
import sklearn.metrics as metrics
print(metrics.classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6365
           1       1.00      0.99      1.00      1635

    accuracy                           1.00      8000
   macro avg       1.00      1.00      1.00      8000
weighted avg       1.00      1.00      1.00      8000



In [33]:
import sklearn.metrics as metrics
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1598
           1       1.00      0.99      0.99       402

    accuracy                           1.00      2000
   macro avg       1.00      0.99      1.00      2000
weighted avg       1.00      1.00      1.00      2000



In [34]:
# 91% of F1 score

In [35]:
# Parameters eligible for tuning
# Layers
# Neurons
# activation function
# optimizer
# batch_size
# epoch

In [36]:
GridsearchCV
# Methods for ANN HyperparamterTuning
# Two popular packages

# Optuna - Image Classification projects - Very Popular
# RayTune
# HyperOpt

NameError: name 'GridsearchCV' is not defined

In [ ]:
# tag Optuna - Documentation

In [ ]:
import optuna
from optuna_integration import OptunaSearchCV

In [ ]:
#https://optuna.org/

In [ ]:
OptunaSearchCV?

In [ ]:
# Compiling Neural Network - Setting up Loss and Optimizers
classifier.compile(optimizer = 'SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [37]:
classifier.compile?

Signature:
classifier.compile(
    optimizer='rmsprop',
    loss=None,
    loss_weights=None,
    metrics=None,
    weighted_metrics=None,
    run_eagerly=False,
    steps_per_execution=1,
    jit_compile='auto',
    auto_scale_loss=True,
)
Docstring:
Configures the model for training.

Example:

```python
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=keras.losses.BinaryCrossentropy(),
    metrics=[
        keras.metrics.BinaryAccuracy(),
        keras.metrics.FalseNegatives(),
    ],
)
```

Args:
    optimizer: String (name of optimizer) or optimizer instance. See
        `keras.optimizers`.
    loss: Loss function. May be a string (name of loss function), or
        a `keras.losses.Loss` instance. See `keras.losses`. A
        loss function is any callable with the signature
        `loss = fn(y_true, y_pred)`, where `y_true` are the ground truth
        values, and `y_pred` are the model's predictions.
        `y_true` should have shape `(batch_siz

In [57]:
import warnings
warnings.filterwarnings('ignore')

In [59]:
from scikeras.wrappers import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense
import optuna
from optuna_integration import OptunaSearchCV

In [40]:
def create_model(n_layers=1):
    model = Sequential()
    model.add(Dense(units=6, activation='relu', input_dim=9)) 
    
    for i in range(n_layers - 1):
        model.add(Dense(units=6, activation='relu'))
        
    model.add(Dense(units=1, activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [41]:
KerasClassifier?

Init signature:
KerasClassifier(
    model: Union[NoneType, Callable[..., keras.src.models.model.Model], keras.src.models.model.Model] = None,
    *,
    build_fn: Union[NoneType, Callable[..., keras.src.models.model.Model], keras.src.models.model.Model] = None,
    warm_start: bool = False,
    random_state: Union[int, numpy.random.mtrand.RandomState, NoneType] = None,
    optimizer: Union[str, keras.src.optimizers.optimizer.Optimizer, Type[keras.src.optimizers.optimizer.Optimizer]] = 'rmsprop',
    loss: Union[str, keras.src.losses.loss.Loss, Type[keras.src.losses.loss.Loss], Callable, NoneType] = None,
    metrics: Optional[List[Union[str, keras.src.metrics.metric.Metric, Type[keras.src.metrics.metric.Metric], Callable]]] = None,
    batch_size: Optional[int] = None,
    validation_batch_size: Optional[int] = None,
    verbose: int = 1,
    callbacks: Optional[List[Union[keras.src.callbacks.callback.Callback, Type[keras.src.callbacks.callback.Callback]]]] = None,
    validation_spli

In [42]:
wrapped_classifier = KerasClassifier(model=create_model, n_layers=1, verbose=0)

In [43]:
param_distributions = {
    "model__n_layers": optuna.distributions.IntDistribution(1, 3),
    "optimizer__learning_rate": optuna.distributions.FloatDistribution(1e-5, 1e-1, log=True)
}

In [44]:
OptunaSearchCV?

Init signature:
OptunaSearchCV(
    estimator: "'sklearn.base.BaseEstimator'",
    param_distributions: 'Mapping[str, distributions.BaseDistribution]',
    *,
    cv: "int | 'BaseCrossValidator' | Iterable | None" = None,
    enable_pruning: 'bool' = False,
    error_score: 'Number | float | str' = nan,
    max_iter: 'int' = 1000,
    n_jobs: 'int | None' = None,
    n_trials: 'int | None' = 10,
    random_state: 'int | np.random.RandomState | None' = None,
    refit: 'bool' = True,
    return_train_score: 'bool' = False,
    scoring: 'Callable[..., float] | str | None' = None,
    study: 'study_module.Study | None' = None,
    subsample: 'float | int' = 1.0,
    timeout: 'float | None' = None,
    verbose: 'int' = 0,
    callbacks: 'list[Callable[[study_module.Study, FrozenTrial], None]] | None' = None,
    catch: 'Iterable[type[Exception]] | type[Exception]' = (),
) -> 'None'
Docstring:     
Hyperparameter search with cross-validation.

Args:
    estimator:
        Object to use to f

In [45]:
optuna_search = OptunaSearchCV(
    estimator=wrapped_classifier, 
    param_distributions=param_distributions, 
    n_trials=5, 
    cv=3,
    error_score='raise'
)

C:\Users\sneha\AppData\Local\Temp\ipykernel_14264\379159384.py:1: ExperimentalWarning: OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.
  optuna_search = OptunaSearchCV(


In [ ]:
optuna_search.fit(X_train, y_train)

[I 2026-06-04 16:09:33,100] A new study created in memory with name: no-name-4c4b31b4-4e34-44c8-9dfa-7b1f92a7d4b0
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\sneha\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` o

In [91]:
optuna_search.best_params_

{'model__n_layers': 3, 'optimizer__learning_rate': 0.001002824063808306}

In [92]:
optuna_search.best_score_

0.8503681507178444

In [93]:
best_model = optuna_search.best_estimator_

In [94]:
y_pred_test_cv = best_model.predict(X_test)
y_pred_test_cv_optimized = (y_pred_test_cv > 0.5)

In [95]:
y_pred_train_cv = best_model.predict(X_train)
y_pred_train_cv_optimized = (y_pred_train_cv > 0.5)

In [96]:
print(classification_report(y_train, y_pred_train_cv_optimized))
print(classification_report(y_test, y_pred_test_cv_optimized))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      6388
           1       0.00      0.00      0.00      1612

    accuracy                           0.80      8000
   macro avg       0.40      0.50      0.44      8000
weighted avg       0.64      0.80      0.71      8000

              precision    recall  f1-score   support

           0       0.79      1.00      0.88      1575
           1       0.00      0.00      0.00       425

    accuracy                           0.79      2000
   macro avg       0.39      0.50      0.44      2000
weighted avg       0.62      0.79      0.69      2000



In [128]:
# End of the Notebook